M48
; DRILL file {KiCad 8.0.1} date 2024-05-05T07:35:21+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-05-05T07:35:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X7.6167Y-1.7323
X7.8077Y-1.7323
T2
X7.6049Y-1.613
X7.8195Y-1.613
M30
